/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AdminDelete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminGet": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminJob": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminList": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminReindex": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Chunk": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ChunkDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Embed": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmbedDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Ingest": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IngestDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IngestFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Meta": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Query": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Upload": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}