/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Accounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AdminDelete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminGet": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminList": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminReindex": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AdminUpdate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Billing": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BillingAccount": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CleanupAdapter": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IngestAdapter": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IngestFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Meta": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Pipeline": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PipelineDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Plans": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Query": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RateLimits": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Tags": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TagsCreate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TagsDelete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TagsList": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TagsUpdate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Upload": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}
